version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "SonarQubeToken"
    SONARQUBE_ENDPOINT: "SonarQubeEndpoint"
phases:
  pre_build:
    commands:
     - "echo Logging in to Amazon ECR..."
     - "aws --version"
     - "$(aws ecr get-login --no-include-email --region us-east-2)"
     - REPOSITORY_URI=479659824361.dkr.ecr.us-east-2.amazonaws.com/fargate-checkin
     - "IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
     - "echo $IMAGE_TAG"
  build:
    commands:
      - echo Build started on `date`
      - echo Starting Java Build...
      - wget --user=admin --ask-password https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
      - unzip sonar-scanner-cli-3.0.3.778-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.0.3.778-linux/bin/
      - mvn clean package docker:build -DpushImageTag
  post_build:
    commands:
      - echo Writing image definitions file...
      - echo $REPOSITORY_URI
      - echo $IMAGE_TAG
      - printf '[{"name":"prueba-concepto-container","imageUri":"479659824361.dkr.ecr.us-east-2.amazonaws.com/prueba-concepto-repository:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

