version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
	  - echo $CODEBUILD_SRC_DIR
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - '**/*'